# Generated by Django 4.2.7 on 2025-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
